### ISSUE TITLE
[enhancement] The 'onedit' hook does not capture the original event

### ISSUE THREAD

**Issue by gfouquet** [NicolasCARPi/jquery_jeditable#103]
Fore some reason, I need to capture the event which triggered the edition mode as an argument of the "onedit" event handler.

**Comment by gfouquet** [comment]
Closed means... you're not OK with the proposal and won't accept the PR ?

**Comment by NicolasCARPi** [comment]
Hello,

I didn't see that this issue was linked to a PR. I closed it because it looked incomplete, but with a PR it makes more sense!

I have added your code to the experimental branch. I couldn't do a proper merge because of conflicts, but you're mentioned in the commit message, I hope this is okay.

Thanks for your contribution :)

Cheers,
~Nico

**Comment by gfouquet** [comment]
Fair enough, I realize my original ticket was rather blunt. 

It's nice to eventually have somebody who maintains this project. Even though I don't use it anymore, former colleagues of mine still do !
