### ISSUE TITLE
Custom html tags in submit cause failure

### ISSUE THREAD

**Issue by kpzani** [NicolasCARPi/jquery_jeditable#69]
If i include custom html tags in the submit attribute then the jeditable never returns back to a normal div.  the form remains. see below

$('.editable').editable( function(value, settings) { 
        //console.log(settings);
         return(value);
      }, { 
         type      : 'textarea',
         tooltip   : 'Click to edit...',
         onblur    : 'ignore',
         height    : '50px',
         //submit   : \"<button type='submit'>ok1</button>\", // this works
         submit     : \"<br /><button type='submit'>ok1</button>\", // this doesnt.
         cancel    : \"<button type='button' class='btn btn-mini btn-danger' style='margin: 5px'><i class='icon-remove icon-white'></i></button>\",  
     });

**Comment by angeliski** [comment]
Hi @kpzani! I get the problem like this:
$('.edit_area').editable(function(val, ev){
				console.log(arguments);
				return val;
			}, {
	         type      : 'text',
	        `  cancel    : '<button type="button" class="btn btn-default">Cancel</button>', `
	        ` submit    : '<button type="button" class="btn btn-default">OK</button>',`
	         tooltip   : 'Click to edit...'
	     });

I belive that this ocorrurs because the form will be submited, if the custom button don't have the type equals submit. What do you think about this @tuupola ?
My work around was put the type submit:

$('.edit_area').editable(function(val, ev){
				console.log(arguments);
				return val;
			}, {
	         type      : 'text',
	        `  cancel    : '<button type="button" class="btn btn-default">Cancel</button>', `
	        ` submit    : '<button type="submit" class="btn btn-default">OK</button>',`
	         tooltip   : 'Click to edit...'
	     });

Because the callback haven't one event for I call e.preventDefault()

**Comment by NicolasCARPi** [comment]
You can now use the cancelcssclass and submitcssclass options to style the buttons, so no need to put html like that anymore ;)
